apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-dapp-deployment
  namespace: poa-kyc-dapp
  labels:
    app: kyc-dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyc-dapp
  template:
    metadata:
      labels:
        app: kyc-dapp
    spec:
      containers:
      - name: kyc-dapp
        image: yuva19102003/poa-kyc-blockchain-network:kycapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kyc-dapp-service
  namespace: poa-kyc-dapp
  labels:
    app: kyc-dapp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: kyc-dapp
