# Dockerfile
FROM ethereum/client-go:alltools-v1.13.15

# Set the .ethereum directory as the working directory
WORKDIR /root

# Copy files into the Docker container
COPY poa.key .
COPY start.sh .

# Expose the bootnode communication port
EXPOSE 30301

# Run the bootnode with the start.sh script
ENTRYPOINT ["sh","start.sh"]