apiVersion: apps/v1
kind: Deployment
metadata:
  name: poa-storage-depolyment
  namespace: poa-kyc-network
  labels:
    app: poa-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poa-storage
  template:
    metadata:
      labels:
        app: poa-storage
    spec:
      containers:
      - name: poa-storage
        image: yuva19102003/poa-kyc-blockchain-network:poastorage # Replace with poa-storage image name if different
        ports:
        - containerPort: 30305
        - containerPort: 8551
        - containerPort: 6061
---
apiVersion: v1
kind: Service
metadata:
  name: poa-storage-svc
  namespace: poa-kyc-network
  labels:
    app: poa-storage
spec:
  type: ClusterIP
  ports:
  - name: ws-port # Name for WebSocket port
    protocol: TCP
    port: 8551
    targetPort: 8551
---
apiVersion: v1
kind: Service
metadata:
  name: poa-storage-node-metrics-service
  namespace: poa-kyc-network
spec:
  type: NodePort # Expose only the metrics port externally
  selector:
    app: poa-storage
  ports:
  - name: metrics-port
    protocol: TCP
    port: 6061
    targetPort: 6061
    nodePort: 30661 # NodePort within the range 30000-32767
  - name: p2p-port # Name for P2P communication port
    protocol: TCP
    port: 30305
    targetPort: 30305
    nodePort: 30305
