apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-1-node-depolyment
  namespace: poa-kyc-network
  labels:
    app: bank-1-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-1-node
  template:
    metadata:
      labels:
        app: bank-1-node
    spec:
      containers:
      - name: bank-1-node
        image: yuva19102003/poa-kyc-blockchain-network:bank1 # Replace with bank-1-node image name if different
        ports:
        - containerPort: 30306
        - containerPort: 8552
        - containerPort: 6062
---
apiVersion: v1
kind: Service
metadata:
  name: bank-1-node-svc
  namespace: poa-kyc-network
  labels:
    app: bank-1-node
spec:
  type: ClusterIP
  ports:
  - name: ws-port # Name for WebSocket port
    protocol: TCP
    port: 8552
    targetPort: 8552
---
apiVersion: v1
kind: Service
metadata:
  name: bank-1-node-metrics-service
  namespace: poa-kyc-network
spec:
  type: NodePort # Expose only the metrics port externally
  selector:
    app: bank-1-node
  ports:
  - name: metrics-port
    protocol: TCP
    port: 6062
    targetPort: 6062
    nodePort: 30662 # NodePort within the range 30000-32767
  - name: p2p-port # Name for P2P communication port
    protocol: TCP
    port: 30306
    targetPort: 30306
    nodePort: 30306
