# Dockerfile
FROM ethereum/client-go:alltools-v1.13.15

# Set the .ethereum directory as the working directory
WORKDIR /root

# Copy files into the Docker container
COPY . .

# Expose the bootnode communication port
EXPOSE 30304 8550 8545 6060

# Run the bootnode with the start.sh script
ENTRYPOINT ["sh","start.sh"]